"""The 50 official evaluation queries (q001-q050) from Extracto_Preguntas_50_v2.pdf."""

PREGUNTAS = {
    "q001": "¿Cómo está transformando la inteligencia artificial la capacidad de los Estados para prevenir, detectar y contrarrestar amenazas NBQR?",
    "q002": "¿Cómo están empleando los sistemas no tripulados potenciados por IA para aumentar la efectividad de las operaciones militares?",
    "q003": "¿Qué lecciones dejan los conflictos recientes sobre el empleo de inteligencia artificial en operaciones militares?",
    "q004": "¿Qué riesgos representa la escasez de talento especializado en inteligencia artificial para el desarrollo de capacidades de defensa?",
    "q005": "¿Qué implicaciones estratégicas tiene la dependencia de tecnologías extranjeras de IA para la autonomía y la seguridad nacional de Colombia?",
    "q006": "¿Qué riesgos operacionales y jurídicos implica incorporar inteligencia artificial en inteligencia militar sin una doctrina, políticas y protocolos consolidados?",
    "q007": "¿Qué desafíos plantea el empleo de sistemas autónomos o semiautónomos frente al Derecho Internacional Humanitario y la atribución de responsabilidades?",
    "q008": "¿Cómo están empleando las fuerzas militares el análisis de inteligencia asistido por IA, el targeting inteligente y los enjambres de drones, y qué oportunidades representan para países con geografías complejas como Colombia?",
    "q009": "¿Cómo está redefiniendo la inteligencia artificial las tácticas y conceptos de operación en los conflictos armados contemporáneos?",
    "q010": "¿Qué capacidades basadas en IA fortalecen la detección, identificación y neutralización de drones utilizados por actores armados?",
    "q011": "¿Cuáles son las principales barreras para incorporar inteligencia artificial en los procesos operacionales y de inteligencia de las Fuerzas Militares?",
    "q012": "¿Cómo puede la experiencia operacional acumulada por las Fuerzas Militares convertirse en conocimiento útil para entrenar sistemas de inteligencia artificial?",
    "q013": "¿Cuáles son las principales amenazas cibernéticas que afectan el despliegue seguro de sistemas de inteligencia artificial en infraestructuras críticas?",
    "q014": "¿Cómo limita la disponibilidad de infraestructura de cómputo avanzado el desarrollo de capacidades nacionales de inteligencia artificial para defensa?",
    "q015": "¿Qué riesgos estratégicos genera la dependencia de semiconductores y hardware especializado para el desarrollo de capacidades militares basadas en IA?",
    "q016": "¿Qué ventajas estratégicas obtienen los actores que incorporan inteligencia artificial y drones de bajo costo, y cuáles son los riesgos de retrasar la transformación tecnológica en defensa?",
    "q017": "¿Qué restricciones impone el Derecho Internacional en el Espacio en la regulación del uso de armas?",
    "q018": "¿Qué capacidades contraespaciales representan actualmente la mayor amenaza para los sistemas satelitales?",
    "q019": "¿Cómo se está empleando la guerra electrónica para interferir sistemas espaciales y qué incidentes recientes lo evidencian?",
    "q020": "¿Qué incidentes recientes de spoofing han comprometido servicios satelitales y qué vulnerabilidades revelan?",
    "q021": "¿Qué implicaciones militares tienen las maniobras de proximidad y encuentro (RPO) realizadas por satélites?",
    "q022": "¿Qué evidencias existen sobre el desarrollo de armas de energía dirigida con potencial empleo contra activos espaciales?",
    "q023": "¿Cuáles son las principales vulnerabilidades cibernéticas de la infraestructura satelital?",
    "q024": "¿Qué países están desarrollando capacidades láser con potencial empleo contra sistemas espaciales?",
    "q025": "¿Qué implicaciones tendría el despliegue de una capacidad nuclear antisatélite en órbita?",
    "q026": "¿Cuál ha sido el impacto de las pruebas antisatélite sobre la generación de desechos orbitales?",
    "q027": "¿Qué desafíos plantea el uso de inteligencia artificial en las operaciones espaciales?",
    "q028": "¿Qué capacidades estratégicas ha demostrado China mediante operaciones de servicio y reabastecimiento en órbita?",
    "q029": "¿Qué capacidades operacionales evidencian las maniobras realizadas recientemente por satélites rusos en órbita GEO?",
    "q030": "¿Cómo han evolucionado las operaciones espaciales dinámicas dentro de la estrategia espacial estadounidense?",
    "q031": "¿Qué cambios doctrinales han fortalecido el empleo militar de las capacidades espaciales de Corea del Norte?",
    "q032": "¿Qué lecciones ha dejado el conflicto entre Rusia y Ucrania sobre el empleo militar del dominio espacial?",
    "q033": "¿Cómo utilizan los grupos armados ilegales el control territorial para sustituir funciones del Estado y consolidar su influencia sobre las comunidades?",
    "q034": "¿Qué corredores geográficos y territorios estratégicos son priorizados por los grupos armados para fortalecer su control operacional?",
    "q035": "¿Cómo contribuyen las economías ilícitas al deterioro ambiental y al fortalecimiento de los grupos armados en América Latina?",
    "q036": "¿Qué actividades económicas ilegales convergen con la explotación de recursos naturales en zonas de conflicto?",
    "q037": "¿De qué manera el crimen organizado logra fortalecer su capacidad de influencia sobre las instituciones del Estado?",
    "q038": "¿Qué innovaciones tácticas recientes han incorporado los grupos armados para aumentar su capacidad operacional?",
    "q039": "¿Qué capacidades han fortalecido los grupos armados para consolidar y expandir su control territorial?",
    "q040": "¿Cómo utilizan los grupos armados ilegales la imposición de normas de conducta para ejercer control social sobre la población civil en regiones con baja presencia del Estado?",
    "q041": "¿Qué corredores de movilidad y territorios estratégicos son priorizados por los Grupos Armados Organizados (GAO), Grupos Armados Organizados Residuales (GAOR) y Grupos Delictivos Organizados (GDO) para asegurar sus economías ilícitas y fortalecer su control territorial?",
    "q042": "¿De qué manera la minería ilegal de oro financia el fortalecimiento y la expansión territorial de los Grupos Armados Organizados (GAO), Grupos Armados Organizados Residuales (GAOR) y Grupos Delictivos Organizados (GDO) en departamentos como Chocó, Antioquia y Bolívar?",
    "q043": "¿De qué manera el narcotráfico financia el fortalecimiento y la expansión territorial de los Grupos Armados Organizados (GAO), Grupos Armados Organizados Residuales (GAOR) y Grupos Delictivos Organizados (GDO) en departamentos como Norte de Santander, Arauca, Córdoba y el Cauca?",
    "q044": "¿Qué factores incrementan el riesgo de reclutamiento, uso y utilización de niños, niñas y adolescentes en zonas de disputa entre grupos armados organizados?",
    "q045": "¿Cómo afectan las disputas entre grupos criminales la seguridad de la población civil y el incremento de los homicidios selectivos?",
    "q046": "¿Qué minerales estratégicos están siendo utilizados por los grupos armados organizados en Colombia y la región para financiar el conflicto?",
    "q047": "¿Cómo la disputa por el control de rutas aéreas incrementa el tráfico de narcóticos, armas y mercancías de contrabando?",
    "q048": "¿Cómo influyen las dinámicas de exploración y explotación petrolera en la inserción y fortalecimiento de grupos armados que buscan controlar rentas derivadas de recursos estratégicos?",
    "q049": "¿De qué manera el accionar de grupos armados interfiere y obstaculiza el desarrollo de los procesos de restitución de tierras?",
    "q050": "¿Cómo adaptan las organizaciones criminales sus estrategias de control territorial frente a las transformaciones políticas, ambientales, tecnológicas y económicas en América Latina?",
}
